name = "invoice-api"

main = "src/index.ts"

compatibility_date = "2024-04-28"

[triggers]
crons = [
  "0 6 * * *",  # Codziennie o 6:00 UTC: Oznaczanie faktur jako przeterminowane (process-invoices)
  "0 5 * * *",  # Codziennie o 5:00 UTC: Wysyłanie przypomnień (process-reminders)
  "0 6 * * *",  # Codziennie o 6:00 UTC: Przetwarzanie subskrypcji (process-subscriptions)
  "0 7 * * *"   # Codziennie o 7:00 UTC: Wysyłanie zaplanowanych faktur (nowe zadanie)
]
